### PR TITLE
Flag calls to "puts"

### PR DESCRIPTION
**Pull request by JacobNinja**
Suggested in https://github.com/JacobNinja/exercism-analysis/issues/9

Description: Flags any call to `puts`, `p`, or `print`

Analyzer class:
`Exercism::Analyzers::Output`

Result type: `:output`
Feedback type: `:print`

### CODE REVIEW

**Comment by kytrinyx** [comment]
Should this include any method that writes to stdout? (p, puts, print)

I think so, yeah. Maybe even `pp` (provided that there's a require pp statement), though I wouldn't bother with that if it's messy or a pain in the ass.

**Comment by kytrinyx** [comment]
If you have a chance, would you merge this?

**Comment by JacobNinja** [comment]
@kytrinyx merged. This doesn't include the `pp` requirements though.

**Comment by kytrinyx** [comment]
Totally fine :) Thanks!

**Pull request merged**
